[package]
name = "server"
version = "0.0.0"
authors = ["erewh0n <erewh0n@forestforthetrees.ca>", "Izzat Bamieh <eib6@yahoo.com>"]

[dependencies]
actix-web = "0.7.14"
actix = "0.7.7"
tokio = "0.1.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
env_logger = "0.5.13"
futures = "0.1.25"
